Amsterdam/schema-tools

- README.md
- schematools/cli.py
- schematools/db.py
- schematools/importer/base.py
- schematools/importer/geojson.py
- schematools/importer/ndjson.py
- schematools/introspect/geojson.py
- schematools/introspect/utils.py
- schematools/models.py
- setup.py
- tests/conftest.py
- tests/files/afvalwegingen.json
- tests/test_cli.py
- tests/test_geojson.py
Created base class for NDJSON and GeoJSON import.
Fixed GeoJSON introspection.
CLI improvements:
* Make arguments reusable
* Allow importing schemas from a local path.
> GeoJSON import

- schematools/provenance/create.py
In order fully automate the create of a datastructure based upon a dataschema, all the columns are needed.
This adjustment translates the col names if the provenance attribute is defined. If not is gets the orginale version of the column name.
The result is a full column name list witch can be used for automating the datastructure creation.
> Provenance: get translated cols and non translated cols

- schematools/cli.py
- schematools/importer/base.py
- schematools/importer/geojson.py
- schematools/importer/ndjson.py
- schematools/types.py
- setup.py
- tests/conftest.py
- tests/files/meetbouten.json
- tests/test_types.py
- Ability to use a local meta schema (easier during testing)
- Make main geometry flexible (but use 'geometry' as default)
- Make id flexible (but use 'id' as default)
- Fix geojson and ndjson to accommodate above changes
- Add tests
> Add several changes to make meetbouten work

- schematools/cli.py
- schematools/contrib/django/cli.py
- schematools/contrib/django/factories.py
- schematools/contrib/django/management/commands/create_tables.py
- schematools/contrib/django/models.py
- schematools/importer/__init__.py
- schematools/importer/base.py
- schematools/importer/geojson.py
- schematools/importer/ndjson.py
- schematools/introspect/db.py
- schematools/types.py
- setup.py
- tests/__init__.py
- tests/conftest.py
- tests/files/afval.json
- tests/files/meetbouten.json
- tests/files/parkeervakken.json
- tests/test_models.py
- implemented n-m relations
- added unit tests
- introspect can have a (posgres) schema argument
- moved model test from dso into schema-tools
- added 'skip' argument to create-tables mgm. command
> N m relations

- schematools/contrib/django/factories.py
- schematools/contrib/django/models.py
The display field was not passed through to the dynamicmodel.
Resolves: [DS-325]
[DS-325]: https://datapunt.atlassian.net/browse/DS-325
> [DS-325] Show display field (if present)

- schematools/contrib/django/models.py
Tijdens `manage.py import_schemas` worden de modellen nu ook bijgewerkt. Eerder werd de schema inhoud al in de `DatasetSchema` weggeschreven.
> [DS-359] Update the DatasetTable / DatasetField models on import_schemas

- schematools/contrib/django/factories.py
- schematools/utils.py
- setup.py
> Add ttl cache for schema lookups

- schematools/types.py
This logic was written in the 'dso docs', and now upstreamed.
> Fix field.sub_fields to return results for nested table type

- schematools/importer/base.py
- tests/conftest.py
- tests/files/data/gebieden.ndjson
- tests/files/gebieden.json
- tests/test_import.py
When schema has camelCased fieldnames.
Also take provenance into account.
> Add snakecasing during import

- README.md
- setup.py
Een minor version update voor pypi
> new version

- schematools/importer/base.py
- schematools/importer/ndjson.py
- tests/files/data/stadsdelen.ndjson
- tests/files/data/woonplaatsen.ndjson
- tests/files/woonplaatsen.json
- tests/fixtures.py
- tests/test_ndjson.py
E.g. statusCode/statusOmschrijving
> Fix issue with missing field in ndjson blobs

- schematools/importer/__init__.py
- schematools/types.py
- setup.py
- tests/files/woningbouwplannen.json
- tests/test_import.py
When multipleOf is defined in the schema, i.e. 0.01, and the schema is used to create the table; it's value is used to setup the scale within a numeric datatype in de database
> added multipleOf logic to import

- PERMISSIONS.md
- added explanation of database level authorization with Amsterdam Schema
> updated permisssions doc

- schematools/importer/base.py
- schematools/importer/ndjson.py
This is the case for the HR dataset, with a simple (non-compound) primary key
'kvknummer'.
> Fix for situation with a simple primary key not being 'id'

- schematools/validation.py
- tests/files/identifier_ref.json
- tests/test_validation.py
Added validator `IdentPropRefsValidator` that was alluded to in module
level docstring but was not included in the original PR.
> Fix bug in ValidationException.

- schematools/cli.py
Bring the way arguments (schema_url etc.) are used
more in line with the existing cli commands.
> Make the arguments for the validation more consistent

- tests/conftest.py
- tests/django/conftest.py
- tests/django/fixtures.py
Make ugly setup even uglier, but hey, it works.
> Make pytest import django settings and fixtures only when needed.

- setup.cfg
- tests/django/test_models.py
- tests/test_validation.py
Put filterwarnings ignore in pytest configuration (setup.cfg)
and make it more specific.
Import `Callable` from typing
> Implement review suggestions

- src/schematools/contrib/django/factories.py
- src/schematools/types.py
- tests/django/test_models.py
Those should never be temporal.
> Change on-the-fly tableschema of nested objects

- src/schematools/importer/ndjson.py
Value could never become None, because a generator objects is always truthy.
> Fix issue with empty values for object-type fields

- src/schematools/cli.py
Dataset with relations now also need the related datasets to be processed.
> Add --additional-schemas option to validate cli command

- src/schematools/datasetcollection.py
For relation fields, it is sometimes (esp. for temporal datasets) needed
to load the dataset schemas that are the target for the relation.
For DSO all schemas need to be loaded anyway, so in that case this is
not a problem.
For cli commands, processing one dataset schema, an option (-a) has been added
to load additional dataset when needed.
However, this is a bit cumbersome. And, it does not work for Django
management commands.
The DatasetCollection (holding a cache of datasets) now tries to load
a schema from the SCHEMA_URL location on a cache-miss for a dataset.
There is one caveat for DSO Useage.
Because these schemas are loaded from SCHEMA_URL
it is possible that this schema differs from the schema that
is imported into the PostgreSQL table by the DSO `import_schemas`
command.
> Autoload dataset schemas that are not found in the datasets_cache

- src/schematools/contrib/django/models.py
Bugfix. Dataset paths were not set properly when importing schemas.
This update fixes that.
> Paths set correctly when importing

- src/schematools/permissions/auth.py
- src/schematools/types.py
- tests/django/test_models_profile.py
- tests/test_permissions_auth.py
- tests/test_types.py
Some review comments were because GitHub collaped them. This PR provides the fixes.
These changes don't affect DSO-API.
> Extra fixes for PR #169

- src/schematools/contrib/django/factories.py
- src/schematools/events/full.py
Two small schematools fixes. Explanation in de commit messages.
> Loose relation and through id fix

- src/schematools/contrib/django/factories.py
For many to many relations, there was no `related_name` defined.
The addition of a `related_name` was explicitly silenced for the
`additionRelations` implementation.
However, to be able to show addition fields defined on the many to many
through table in the DSO, a `related_name` is essential.
> Add related_name for FKs of M2M relations

- docs/import_event.py
- src/schematools/cli.py
- src/schematools/contrib/django/management/commands/import_profiles.py
- src/schematools/contrib/django/management/commands/import_schemas.py
- src/schematools/contrib/django/models.py
- src/schematools/datasetcollection.py
- src/schematools/utils.py
Fixes bug that caused dataset to not be updated,
when a schema is imported and the path property has changed.
> Fix: Dataset path updated when schema imported

- src/schematools/cli.py
- src/schematools/types.py
- tests/conftest.py
- tests/files/afvalwegingen_clusters-table.json
- tests/files/hr.json
This PR started as a fix for the cli `validate` command.
However, it turned out that the mocking of http requests had gone awry, so that has also been fixed in this PR.
See more explanation in the individual commits.
> Add prefetch schemas to validator

- src/schematools/cli.py
- src/schematools/utils.py
Name should have been `dataset_schema_from_file`. Is now corrected.
> Fix name of util function schema_from_file

- src/schematools/contrib/django/management/commands/change_dataset.py
The argument needs to contain `{table_id}` for DSO-API to insert the actual table name.
> Validate change_dataset's --endpoint-url argument

- src/schematools/types.py
Using a NamedTuple instead of the `Tuple[str, str]` logic.
> Improve typing annotations for DatasetTableSchema.temporal

- src/schematools/contrib/django/factories.py
- src/schematools/contrib/django/management/commands/dump_models.py
- src/schematools/types.py
This displays how the dynamic models are constructed
> Add manage.py dump_models command to show the internal state

- src/schematools/contrib/django/management/commands/dump_models.py
> Improve dump_models to generate parsable Python, and fix flake errors

- src/schematools/contrib/django/models.py
Inspired from feedback from Kees when working on the first tickets.
Moving get_field_schema() call to a place where it would be expected 
This should make it easier to find such logic for newcomers, as things
like get_table_schema() are also found in the same place.
> Make get_field_schema() easier to find

- .pre-commit-config.yaml
- src/schematools/__init__.py
- src/schematools/cli.py
- src/schematools/contrib/django/management/commands/import_schemas.py
- src/schematools/datasetcollection.py
- src/schematools/loaders.py
- src/schematools/types.py
- src/schematools/utils.py
- tests/conftest.py
- tests/test_types.py
- tests/test_validation.py
See the first commit message for explanation about this PR.
> AB#23066 Add configurable loader for datasets

- src/schematools/types.py
`flake8` on this file now passes, though the pre-commit hook will still find a few errors.
Number of `mypy` errors down from 85 to 53.
> flake8 and mypy cleanup in types.py

- src/schematools/cli.py
Some "external" users are starting to use `schematools`
to generate SQL tables from amsterdam schemas definitions.
However, the way the cli works at the moment is mainly
tailored to our use case and needs a full checkout of all the schemas.
This new cli command only needs an isolated amsterdam schema file,
and generates sql create commands from it.
> Add cli command to generate SQL Create statements

- src/schematools/contrib/django/factories.py
- src/schematools/importer/base.py
- src/schematools/importer/ndjson.py
- src/schematools/types.py
- tests/files/meetbouten.json
- tests/files/multirelation.json
- tests/test_ndjson.py
- tests/test_types.py
See explanation in the commit message.
> ab#25069 wrong datasetid in relations

- src/schematools/types.py
No test because this is only debugging code.
> Report table id in SemVer exception message

- src/schematools/validation.py
Final part of #232 that I forgot to commit.
> mypy fixes to validation code

- src/schematools/contrib/django/factories.py
- src/schematools/contrib/django/models.py
- src/schematools/types.py
* Improved tracking reverse relations (by changing the reverse names).
* Improved __repr__ for clarity.
* Fixed the `to_field` for the right-side of loose m2m relations
> Improvements for M2M relationships, fix joining loose relations

- pyproject.toml
- setup.cfg
> Downgrade jsonschema

- pyproject.toml
- setup.cfg
- src/schematools/types.py
And fixed a typvar DTS bound to a non existing type.
> Remove circular dependency in schematools

- src/schematools/cli.py
The argument to validation.run was missing.
> Fix schema validate

- src/schematools/cli.py
The "success!" messages are confusing when they follow errors from the other validation phase: they look like the program reassuring me that what it just printed was noise to be ignored. Just be silent on success.
Closes #260 too.
> Don't print "success!" in schema validate

- src/schematools/validation.py
- tests/files/meetbouten.json
- tests/test_validation.py
Also fixes a bug in another validator and one in a test schema.
> AB#30010 Validate mainGeometry field

- src/schematools/factories.py
- src/schematools/types.py
See commit message for explanation.
> Fix nested table ndjson import

- src/schematools/permissions/auth.py
We don't need to build up a list of permissions in the functions that use `PermissionCollection`: we only ever use the highest permission we find, so track that. Also, the abort_on_highest decorator is "DRY" but much more complicated than just checking if we've found `PermissionLevel.highest` at the start of the loop.
> Remove PermissionCollection and custom control flow

- src/schematools/validation.py
Not sure how I missed this, but I did.
> Adapt validation test to new handling of OPENBAAR

- src/schematools/validation.py
- tests/files/id_auth.json
- tests/test_validation.py
Display field is validated:
* Check the field exists
* Check it does not have an auth property
> AB#41944 Validate display field

- src/schematools/contrib/django/models.py
- src/schematools/types.py
Be consistent with DatasetSchema.has_geometry_fields
> Add DataSchemaTable.has_geometry_fields property

- setup.cfg
- src/schematools/permissions/__init__.py
- src/schematools/permissions/db.py
- src/schematools/validation.py
- tests/test_validation.py
Recently, a public scope "OPENBAAR" has been added to all datasets.
The validator that validates the scopes, should take this PUBLIC_SCOPE
into account.
> Take PUBLIC_SCOPE into account during validation

- setup.cfg
- src/schematools/types.py
This is needed for the filter logic to support reverse relations
> Add DatasetTableSchema.get_additional_relation_by_id()

- tests/test_validation.py
It's really the test that was broken, not the validation logic. Not sure how this happened.
> Fix relation auth validation test

- .pre-commit-config.yaml
- src/schematools/types.py
Number of mypy errors down to 62, from 66.
> Style fixes to types.py and less strict flake8 checking

- src/schematools/.github/CODEOWNERS
Add a CODEOWNERS file so an approval from the team is required for a merge
to main branch
> Add github Codeowners

- tests/test_permissions.py
https://dev.azure.com/CloudCompetenceCenter/Data%20Diensten/_workitems/edit/57386
> Create `write_brk` role the first time its needed

- src/schematools/cli.py
- src/schematools/permissions/db.py
Preparation for [AB#59480](https://dev.azure.com/CloudCompetenceCenter/089b38ee-0066-4b66-a36c-20744a0e4348/_workitems/edit/59480), where I want to change the meaning of the key from id to path.
> Use only .items() of dict[str, DatasetSchema]

- src/schematools/types.py
No need to read the source dict that many times
> Turn many often-used schema fields into cached property.

- src/schematools/utils.py
When a dataset is in a subfolder (e.g. haalcentraalbag), a configuration with a SCHEMA_URL pointing to the local filesystem, does not find these datasets.
This PR fixes that problem.
> AB#60440 (datasets on subpaths)

- .flake8
- src/schematools/contrib/django/factories.py
- src/schematools/contrib/django/models.py
- src/schematools/naming.py
- src/schematools/types.py
- tests/django/test_model_mockers.py
These were spots I've missed in my previous PR.
Also, the model name linking has been improved a lot, making that more consistent and easier to read.
> Fix mode snake/camel issues in schematools

- src/schematools/_datasetcollection.py
- src/schematools/cli.py
- src/schematools/contrib/django/management/commands/import_schemas.py
- src/schematools/contrib/django/schemas.py
- src/schematools/types.py
Gave both the module and its contents underscores, the latter because of re-exports from other modules.
> Make DatasetCollection private

- src/schematools/validation.py
Fixes [AB#60643](https://dev.azure.com/CloudCompetenceCenter/089b38ee-0066-4b66-a36c-20744a0e4348/_workitems/edit/60643).
> Check if table/field names don't repeat dataset/table names

- src/schematools/contrib/django/factories.py
Fixes a regression caused by the 5.0 release
> Fix Django db_column for subfields that use shortnames

- CHANGES.md
- setup.cfg
- src/schematools/factories.py
- src/schematools/importer/base.py
tested with 'dataverwerkingen' that this fixes their airflow jobs.
> Fix importer to handle snake-cased table ID's in other cases too.

- src/schematools/factories.py
The old index_factory() logic (in 6951758398444d989399e2f16272d1e56b7d1325) also had try-catch logic for tables that didn't exist. It was unclear why that functionality was there. This commit restores it.
> Fix KeyError in index creation when tables are skipped with limit_tables_to

- src/schematools/importer/base.py
The previous importer logic (from 6951758398444d989399e2f16272d1e56b7d1325) implicitly did this by iterating over the insert_statements, and therefore silently dropping records that didn't have a corresponding table.
This new logic can detect the issue and warn for it so invalid importer logic won't silently drop records.
> Fix importer to skip M2M table data when limit_tables_to is used.

- src/schematools/types.py
Spotted at https://github.com/Amsterdam/amsterdam-schema/pull/554.
> Better error message for wrong type

- src/schematools/loaders.py
This corrects changes by e9dc47c00f538f70415bb37a6761e30bc2a8a62e
> Fix unit testing due to changes in relative schema imports

- src/schematools/contrib/django/factories.py
- src/schematools/contrib/django/models.py
- src/schematools/loaders.py
- src/schematools/types.py
All made while writing the upcoming `sqlmigrate_schema` command. See messages for each commit.
> Various minor schematool type improvements

- src/schematools/contrib/django/management/commands/remove_schemas.py
The remove_schemas command expects snake-cased dataset identifiers. If the caller accidentally uses the camel-cased id, it now detects that and prints a suggestion:
These schemas do not exist:
* 'brk2' (did you mean 'brk_2'?)
> Catch snake-casing errors in remove_schemas

- setup.cfg
- src/schematools/importer/ndjson.py
All tests pass except the ones for mocking.
> Bump version + small refactor

- src/schematools/cli.py
So also on table files, if those were changed but the associated dataset.json was not.
> Fix schema batch-validate to work on any schema file

- src/schematools/importer/ndjson.py
> Add `neuronId` to throughtable id mapping

- CHANGES.md
- setup.cfg
> Bump to 5.1.6

- src/schematools/ckan/_convert.py
Apparently, titles are identifiers. Leaves me wondering what the identifier field is for, because its output never shows up anywhere.
Fixes [AB#61176](https://dev.azure.com/CloudCompetenceCenter/089b38ee-0066-4b66-a36c-20744a0e4348/_workitems/edit/61176).
> Hack to make CKAN uploader work with data-acc.overheid.nl

- CHANGES.md
- setup.cfg
- src/schematools/cli.py
- src/schematools/loaders.py
> Schematools 5.5.0: bugfixes in batch_validate

- .github/workflows/test.yaml
- tests/conftest.py
- tests/django/conftest.py
- tests/django/test_mocking.py
- tests/django/test_models.py
- tests/test_permissions.py
Fixes [AB#65521](https://dev.azure.com/CloudCompetenceCenter/089b38ee-0066-4b66-a36c-20744a0e4348/_workitems/edit/65521).
> Run database tests with Postgres in CI/CD

- CHANGES.md
- setup.cfg
> Pin SQLAlchemy to < 1.4.0

- setup.cfg
- src/schematools/cli.py
- src/schematools/exports/__init__.py
- src/schematools/exports/csv.py
- src/schematools/exports/geopackage.py
- src/schematools/exports/jsonlines.py
- src/schematools/permissions/db.py
- tests/files/datasets/brk.json
- tests/files/datasets/kadastraleobjecten.json
> AB#71985 export data from amsterdam schema datasets

- CHANGES.md
- setup.cfg
- src/schematools/types.py
Should fix the DSO-API docs, which are currently broken.
> Make publisher handling code even more complicated

- .github/workflows/test.yaml
- setup.cfg
Straight from https://docs.github.com/en/actions/using-containerized-services/creating-postgresql-service-containers.
> CI/CD: add healthcheck for PostgreSQL

- CHANGES.md
- setup.cfg
- src/schematools/contrib/django/management/commands/create_views.py
It did not take into account the `OPENBAAR` scope in the correct way.
Furthermore, use more sets in the scope operation. Because sets are honking great!
> Fix the _check_required_permissions_exist

- Dockerfile
Replace old unsupported amsterdam/python image with bookworm based official Python image
> AB#92881 Use official Python image

- CHANGES.md
- setup.cfg
- src/schematools/types.py
[AB#114790](https://dev.azure.com/CloudCompetenceCenter/089b38ee-0066-4b66-a36c-20744a0e4348/_workitems/edit/114790) Add unit property from amsterdam-schema to field type.
> Yrob/add AB#114790 units to fields

- CHANGES.md
- setup.cfg
- src/schematools/cli.py
- src/schematools/loaders.py
- src/schematools/validation.py
- tests/test_validation.py
Deze zal worden gebruikt in amsterdam-schema om te valideren of aangepaste of gebumpte tabellen geen breaking changes introduceren.
> Add validate tables command

- CHANGES.md
- setup.cfg
- src/schematools/types.py
- tests/files/datasets/gebieden.json
- tests/test_types.py
Zelfde code als de PR tegen master.
> v6: Add zoom props to table

- CHANGES.md
- setup.cfg
- src/schematools/cli.py
- src/schematools/exports/__init__.py
- src/schematools/exports/csv.py
- src/schematools/exports/geojson.py
- src/schematools/exports/geopackage.py
- src/schematools/exports/jsonlines.py
- tests/test_export.py
* Added GeoJsonExporter
* Added export geojson
* Added test_geojson_export
> Added support for GeoJSON exports

- src/schematools/cli.py
Dit verhoogt de performance van de validatie enigszins, vooral bij het checken van een groot aantal bestanden.
> Instantiate json validators only once

- CHANGES.md
- setup.cfg
> Bump to v7.5.4

- CHANGES.md
- setup.cfg
- src/schematools/contrib/django/management/commands/import_schemas.py
- tests/django/test_models.py
- tests/django/test_schema_import.py
- tests/django/test_schema_removal.py
> dry run by default

- CHANGES.md
- setup.cfg
- src/schematools/contrib/django/management/commands/import_schemas.py
so we don't migrate v2 to v3...
> Confirm version before migrate

- CHANGES.md
- setup.cfg
- src/schematools/cli.py
- src/schematools/permissions/db.py
- tests/test_permissions.py
Dit maakt rollen aan voor alle scopes.
> Missing roles for unused scopes

- .github/workflows/test.yaml
- CHANGES.md
- setup.cfg
- src/schematools/contrib/django/management/commands/create_views.py
- src/schematools/contrib/django/management/commands/remove_schemas.py
- src/schematools/exports/__init__.py
- src/schematools/exports/csv.py
- src/schematools/exports/geopackage.py
- src/schematools/exports/jsonlines.py
- src/schematools/factories.py
- src/schematools/importer/base.py
- src/schematools/permissions/db.py
- tests/conftest.py
- tests/test_permissions.py
toch wel handig om het ook hier te doen, anders moet ik twee PRs in DSO tegelijk mergen
> psycopg3 schematoolsv7

- CHANGES.md
- setup.cfg
- src/schematools/contrib/django/management/commands/migration_helpers.py
- this caused a bug because we tried to clear cache (with del) that didn't exist yet. 
- tested by locally running the command.
> Clear app labels properly

- CHANGES.md
- setup.cfg
- src/schematools/exceptions.py
- src/schematools/loaders.py
Samen met [deze](https://github.com/Amsterdam/amsterdam-schema/pull/1403) zorgt dit ervoor dat alle profielen goed laden.
> Load profiles nested by team

- setup.cfg
- src/schematools/loaders.py
publish schemas haalt alle extensies eraf
> Bugfix json extension

- Makefile
- README.md
& add more instructions in docs
> update upload (pypi) command

- CHANGES.md
- setup.cfg
- src/schematools/factories.py
- src/schematools/permissions/db.py
- src/schematools/types.py
- tests/files/datasets/auth_on_multiple_versions.json
- tests/test_permissions.py
De permissies werden alleen toegepast voor tabellen die behoren tot de default versie, bij deze is dat gefixt zodat alle tabellen de juiste permissies krijgen.
> Fix permissions for non default tables

- .github/workflows/deplic.yaml
- .github/workflows/pre-commit.yml
- .github/workflows/test.yaml
Branch protection has been set, this ensures actions are run on PRs against them.
> run actions on schema-tools-v* branches

- CHANGES.md
- setup.cfg
- src/schematools/contrib/django/management/commands/import_schemas.py
- tests/django/fixtures.py
- tests/django/test_schema_import.py
- tests/django/test_schema_removal.py
- Compare datasets and delete datasets if missing
- Tests for comparing and deleting datasets
- Added management commands to import scopes and publishers
> Delete datasets when dataset.json schema is deleted
