- schematools/maps/__init__.py
- schematools/maps/create.py
- schematools/maps/generators/mapfile.py
- setup.py
Remove code dependencies on `amsterdam_schema` app.
> Bugfix. Amsterdam_schema app is not used anymore.

- schematools/contrib/django/models.py
- tests/conftest.py
To prevent spaces in urls
And fixed the test, the tests assumed hard-coded schema url
> Slugify dataset and table ids

- schematools/contrib/django/factories.py
- schematools/utils.py
- setup.py
Minor fix for Nullable fields in django.
Primary key can not be null and we can safely set `CASCADE` for not nullable fields.
> Fixing errors delated to NULLable fields in models.

- schematools/types.py
- setup.py
This PR allows parsing of `additionalFilters` schema parameter and transforms it into new additional filters that are mapped to one or multiple fields.
Including `effective` filter that will create Range filter `start__lte=x` & `end__gt=x`.
Schema will look as follows:
```
"tables": {
"x":  {
"schema":  {
...
"additionalFilters": {
"effective": {                                     << Filter name. For now we have only `effective`.
"name": "regimes.inWerkingOp",  << String to be presented in URI.
"start": "regimes.begin tijd",          << Start field name. Relations are separated with dots.
"end": "regimes.eind tijd"              << End field name. Relations are separated with dots.
}
},
"properties": {...}
}
```
Full example: https://github.com/Amsterdam/dso-api/pull/47/files#diff-b4fad29b …
> Expose filters schema property.

- schematools/types.py
- setup.py
Adding `identifier` and `temporal` properties to DatasetSchema
`identifier` to be used later as URL parameter
`temporal` is a configuration that affects API views, allowing "travel through time"
> Temporal properties.

- schematools/contrib/django/factories.py
- schematools/contrib/django/management/commands/change_dataset.py
- schematools/contrib/django/models.py
- setup.py
Allow managing `enable_geosearch` setting via command line.
> Disable geosearch

- schematools/contrib/django/factories.py
- setup.py
If for a forward relation no additionalRelations have been defined in the target table
set related_name to + so that  no backwards relations are  defined in the Django model
Otherwise set the related_name for to the matching name in the additionRelations definition
> DS-339 For backwards relations add related_name

- schematools/contrib/django/factories.py
- setup.py
Nog een bugje, schema-tools ging in meta-model definitie nog uit van het bestaand van een 'id' veld. We hebben nu met rioolknopen een eerste dataset tabel waarin deze ontbreekt.
> Fix ordering

- schematools/cli.py
- schematools/models.py
Gebruik pg schema "meta" en nieuwe tabelnamen. Vervang array datatypes door strings (wordt komma-separated aangeleverd)
> Change source tables for ruimte relational amsterdam schemas

- schematools/contrib/django/management/commands/import_schemas.py
- schematools/contrib/django/models.py
Changed create_tables default to False
That is more convenient locally (because of the brp dataset)
> Add datetime model lookup

- schematools/contrib/django/factories.py
- schematools/contrib/django/models.py
Usage in the Amsterdam schema definition:
- "type" : "string"
- "format" : "uri"
The format uri specification translates it URLfield django definition, which is stored as a charfield type with default value length 200 char.
> added the option uri as definition for format

- schematools/importer/base.py
- schematools/importer/ndjson.py
- schematools/types.py
- tests/conftest.py
- tests/files/data/kadastraleobjecten.ndjson
- tests/files/kadastraleobjecten.json
- tests/test_ndjson.py
Make names more specific for both sides of the relation.
This avoids name-clashes for self-referencing nm-relations
Add the left-side values of an nm-relation for compound keys
> Fix the fields for an nm-relation

- schematools/contrib/django/factories.py
- schematools/types.py
- tests/test_models.py
Recent rename of the target table columns was not
yet changed for the Django models
> Fix columnames for nm-through tables

- schematools/cli.py
- schematools/permissions.py
- tests/test_permissions.py
All database activities of the permissions CLI are now in a single transaction, to allow automatic rollback if something goes wrong.
The CLI interface is a bit cleaner, see `schema permissions apply --help` for options.
A typical way to invoke it would be:
`schema permissions apply --create-roles --auto --revoke --dry-run`
this creates missing db group roles, revokes any old table/column permissions, and sets new permissions according to scope.
(change `--dry-run` for `--execute` to actually run it).
`--auto` means that scope `ABC/DEF` will be associated to group role `scope_abc_def`.
> Permissions ext

- django_tests/test_models.py
- schematools/contrib/django/factories.py
- schematools/contrib/django/managers.py
- schematools/contrib/django/models.py
- tests/files/woningbouwplannen.json
- tests/fixtures.py
LooseRelationManyToManyField is a custom field, used when a non-temporal dataset refers many-to-many to a temporal dataset. 
In the non-temporal dataset (the source) we get an array of identifiers, which refer to temporal objects (the target) having both an identifier and a sequence number (volgnummer). The volgnummer is unspecified, making it impossible to have an exact foreign key relation, but when viewed we want to see the latest (highest) one. This is being resolved in the dso-api serializer.
> Loose n m relations

- schematools/importer/base.py
- schematools/types.py
- tests/files/brk.json
- tests/fixtures.py
- tests/test_indexes.py
- tests_django/test_models.py
In types.py a DB_NAME instance method is used for getting the DB name of a table.
In the future, it can be used to look up the SHORTNAME in the Amsterdam Schema definition
to accomodate table names that can exceed the Postgres DB limit of 63 characters.
The DB_NAME instance method must also deal with n:m tables (through tables).
The Index name creation on n:m tables uses the DB_NAME method to look up the table name to apply its index.
Defining the DB_NAME instance method in types.py on - at first - class DatasetTableSchema, set a placeholder for a the Amsterdam Schema look up in the near future.
For now, it uses an existing function that defines the table name which is also used in the baggob data processing.
> [DS-514] DB_NAME instance method for getting table name

- schematools/events/__init__.py
- schematools/types.py
- tests/conftest.py
- tests/files/ggwgebieden.json
- tests/test_events.py
- tests/test_ndjson.py
- tests_django/test_auth_backend.py
Temporal dimension fields (begin_geldigheid, eind_geldigheid) were inserted to the Django models (for temporary dataset-tables) by default. However, most of the current database tables do not have these fields, because the current ndjson import does not provide these fields. The generation of dimension fields is now made configurable and switched off by default.
> Make temporal dimension fields optional

- schematools/permissions.py
- schematools/utils.py
In order to use the permissions as an operator in Airflow, the permissions logic should take a single dataset schema and set the permissions for the underling objects.
Because data processing in Airflow can make objects to drop, the set permissions are also deleted. DB users are effected by this. One of the solutions is the grant the privileges again. To use it sparingly, the permissions can be set on one single dataset (and it's underling objects).
> [PERMISSIONS] add posibility to set DB permissions for single dataset

- schematools/contrib/django/auth_backend.py
- schematools/contrib/django/models.py
- tests_django/test_auth_backend.py
* generate_permission_key() is called many times, and benefits from lru_cache()
* RequestProfile.get_all_permissions() wrongly cached data.
* RequestProfile.get_all_permissions() was called per-field, with caching it
should be per-table. Hence the name change to get_table_permissions()
> Fix performance of permission retrieval

- schematools/cli.py
- schematools/permissions.py
- tests/test_permissions.py
Extended the permissions CLI to create roles with DML rights:
- For each dataset create one write_{dataset.id} role with strict DML rights (without SELECT)
- The write_ roles can be created for all datasets at once (Jenkins), or per dataset (Airflow).
- The write_ roles will be created by default, so that no change is required in Jenkins or Airflow
- The mdbdataservices_roles role has been extended to include grant-able DML privileges
- Added pytests
- Fixed some minor spelling, function names, and formatting
> For each dataset generate a write role with DML rights (DS-576)

- schematools/__init__.py
- schematools/importer/base.py
- schematools/types.py
- setup.py
- tests/test_indexes.py
The index creation logic was missing the creation of a databas index based on columns in a child table that refer to a parent table. The so called foreign key contraint is not enforced in the database. Yet the relevant columns are used in the API for retreiving the data. Also it can be used by database users who query on the tables directly.
> Complete existing index creation (1:N relation reference)

- schematools/contrib/django/models.py
- schematools/importer/__init__.py
- setup.py
- tests/files/woningbouwplannen.json
- tests/test_import.py
Some sources provide us with an own id value. The value size of these source id's can exceed the maxinum of 32 bytes of the standard int(4) datatype in the database. During data load processing data from source into target table, the flow in Airflow can crash. Therefore the is a support added for bigint. Returing a 64 bytes int(8) datatype in the database.
> Added bigint as datatype

- schematools/importer/base.py
- tests/files/data/woonplaatsen.ndjson
- tests/files/woonplaatsen.json
- tests/test_ndjson.py
In case the schema fieldname is equal to the key used
in the ndjson import. This case was not covered yet.
> Fix provenancing for jsonpath

- schematools/utils.py
- tests/test_utils.py
Given
>>> s = 'a_pretty_long_identifier_in_snake_case'
I get the following timeit results. Current implementation, with the @lru_cache decorator removed:
>>> %timeit toCamelCase(s)
10.4 µs ± 18.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
New version:
>>> %timeit toCamelCase(s)
4.88 µs ± 15.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
The LRU decorator is still there, since this is still a factor two below cache lookup speed:
>>> %timeit toCamelCase(s)
2.29 µs ± 21.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
> Optimize toCamelCase

- schematools/contrib/django/models.py
- setup.py
Renaming confusing method name in order to give more clarity (and allow `get_dataset` method to be added in future).
> Rename DynamicModel.get_dataset into DynamicModel.get_dataset_schema for clarity

- schematools/contrib/django/models.py
- tests/conftest.py
The shortnames possibily for tables created a subtle bug
when reloading schemas with the `reload_schemas` mgm command.
> [4390] fix reload_schemas issue

- schematools/contrib/django/factories.py
- schematools/contrib/django/management/commands/create_tables.py
- schematools/contrib/django/models.py
- schematools/types.py
- schematools/utils.py
- setup.py
- tests/test_utils.py
This PR does:
- add `get_dataset()` method to `DynamicModel` class, allowing connection between `Dataset` and `DynamicModel` models.
- parses subfolders and uses path as `Dataset.url_prefix` for future reuse in urls.
> AD#5018 Dataset Subpath's

- schematools/importer/base.py
- tests/test_indexes.py
Table factory should take postfix (_new) into account
Index creation for through tables should use db_name()
Tests should use db_name()
Added long name to a testschema to prove that it does
not crash index creation.
> Fix failure of index creation on long field names

- src/schematools/validation.py
These became apparent after DSO API developere documentation
started including the `schematools` API docstrings.
These things are found earlier and easier once we start creating Sphinx
based documentation for this project as well.
Not bumping version number. These fixes will percolate to DSO API on the
next available PR.
> Fix small docstring issues.

- src/schematools/contrib/django/management/commands/import_schemas.py
🤦  initial import would update all datasets with `_none` suffix.
This PR fixes that.
> Fix bug in initial importer logic.

- src/schematools/contrib/django/models.py
Overal wordt `has_parent_table()` aangeroepen, maar dit checkt niet op M2M through tabellen
> Make sure Dataset.has_parent_table() also hides M2M through tables

- README.md
The pre-commit hook should not check the meta schema against itself.
Hence it requires an adjusted `exclude` argument.
> Update pre-commit hook doc to exclude mete schema.

- tests/django/test_models.py
- tests/test_indexes.py
- tests/test_validation.py
- Fix deprecation for MetaData.reflect()
- Fix deprecation for Callable (should be imported from collections.abc)
- Ignore the RuntimeWarning about "Model was already registered"
Beause suppressing the warnings is not threadsafe, it is not
implemented for the DSO Django code, because that could
throw away relevant warnings.
> Get rid of warnings during test runs.

- src/schematools/importer/base.py
- src/schematools/types.py
- tests/test_import.py
On request of datateam ruimte the descriptions of tables and fields in the schema definition are used as comment values in the database for tables and columns.
> Table and column comments for creating table based on schema

- pyproject.toml
- setup.cfg
- src/schematools/importer/base.py
- tests/test_import.py
- tests/test_indexes.py
Currently in Airflow an operator is used in serval dags to create the database objects (tables) that are defined in the dataschema definition (JSON schema). It defaults to the DB schema public. 
In some dags the tables are first created in a different schema then public before moved to public. Therefor it could be necessary to create the objects in a different DB schema then public. The DB schema name is added to specify the DB target schema. When not specified it defaults to public.
> [AB#6837] add DB schema name as parameter for table creation

- pyproject.toml
- setup.cfg
- src/schematools/importer/base.py
- tests/test_import.py
- Extra test to check temporay table name when using existing db_table_name argument
- Adjustment index factory to deal with db_table_name (which wasn't tested properly yet)
>  Extra test and usage of existing db_table_name as a way to define temporary table name

- pyproject.toml
- setup.cfg
- src/schematools/contrib/django/models.py
- tests/django/test_models.py
Added the cached property `has_geometry_fields` to Dataset. This is just a copy of the `dataset_has_geometry_fields` function currently in dso-api wfs view, and should replace it. The functionality is needed in multiple locations so I moved it here.
> Dataset has cached property has_geometry_fields

- setup.cfg
`flake8` has a default ignore list. Reason being that, according to its
maintainer on the podcast https://testandcode.com/156?t=230, PEP8 has
flip flopped on certain style recommendations over the years. So
`flake8` simply adds those to the default ignore list. In addition there
are number of style checks that are each other's opposite. These are
added to the default ignore list as well.
So when specifying your own `ignore` list these default values are
overwritten. Hence it's better to extend the ignore list by means of the
`extend-ignore` option. And that's what I'm doing in this commit.
BTW I'm removing the W503 rule. It's already part of the default ignore
list.
> flake8: use extend-ignore instead of ignore.

- src/schematools/contrib/django/management/commands/import_profiles.py
- src/schematools/utils.py
- tests/test_utils.py
Allow `dataset`/`profile` path to have no subpaths.
> Fix edge case with in profile loading process

- src/schematools/contrib/django/factories.py
- src/schematools/types.py
- src/schematools/utils.py
Separate commit to fix the typings in types.py (and utils.py).
Changed some optional parameters (id, parent) for table and field to mandatory (non-keyword) parameters,
because the parameters are always needed anyway. This simplified the `mypy pleasing` quite a bit.
> Fix types in typing.py

- src/schematools/contrib/django/factories.py
- src/schematools/events/full.py
Temporal information has been moved down from dataset to table.
However, the main identifier (usually "identificatie") was still
obtained from the dataset. Thas been now been corrected.
> Use the identifier from the table for temporality

- src/schematools/importer/base.py
- src/schematools/importer/ndjson.py
Team BK introduced a camelcased shortname for a table
(hr.maatschappelijkeactiviteiten).
This was not handled correctly in ndjson importer
and has been fixed by this commit.
> Fix casing-issues for shortnames on datasettable

- src/schematools/contrib/django/factories.py
- src/schematools/types.py
- tests/django/test_models.py
These db_columns were not correct when the source table
was using a `shortname`, leading to SQL errors in DSO API
> Fix db_column names to source of nm relation

- src/schematools/events/full.py
- src/schematools/importer/base.py
- src/schematools/importer/ndjson.py
- src/schematools/types.py
- tests/test_events_full.py
- tests/test_ndjson.py
The temporal fields for "geldigheid" need to be taken from
the through table. However, to be able to query for these fields
in DSO API, this through table needs to have a non-compound primary key.
This PR adds such a PK field and adjusts the imports to give this
PK field the value of the concatenation of both sides of the relation.
> AB#4378 Add id column for through tables

- src/schematools/importer/base.py
An extra singular `id` field has been added as PK to the through tables. For efficiency, an index need
> Make the `id` column for through table a PK

- pyproject.toml
- setup.cfg
- src/schematools/importer/base.py
The check was done for foreign keys, but not for indices. This corrects
that.
> Fix: check max ident length for indices.

- src/schematools/types.py
- tests/files/gebieden_sep_tables/bouwblokken/v1.0.0.json
- tests/files/gebieden_sep_tables/buurten/v1.0.0.json
- tests/files/gebieden_sep_tables/dataset.json
- tests/test_types.py
Bugfix Datasets with tables in separate files (table references)
load correctly when read from a local file.
Dit zorgt dat `schema validate` op lokale datasets met losse tabellen werkt.
> AB#17588 Datasets with table refs load from file

- src/schematools/permissions/__init__.py
- src/schematools/permissions/auth.py
- tests/test_permissions_auth.py
Just passing the scopes to the `UserScopes` constructor makes the code easier to work with (to debug especially). It also means that we can introduce more sensible logging than the per call logging done by `authorization_django`, especially in `UserScopes.has_any_scope`, which can do many `is_authorized_for` calls.
> [AB#6554] Decouple UserScopes from is_authorized_for

- src/schematools/contrib/django/app_config.py
Avoids unneeded warnings during tests
> Fix unneeded DisableMigrations warning, as it already disabled migrations

- pyproject.toml
- setup.cfg
- src/schematools/types.py
- tests/conftest.py
- tests/files/not_a_json_file.txt
- tests/test_types.py
Now that we are splitting out tables from datasets into separate JSON
files, we can't assume anymore that every JSON file is a dataset. Hence
dataset specific operations should verify they are actually dealing with
a dataset first.
> AB#9078 Only reference tables from datasets

- src/schematools/cli.py
- src/schematools/utils.py
And furthermore, add `prefetch_related` flag to be able to load
the datasets that are associated with the requested dataset
through relations.
This function is needed, because the github actions validation hooks
are fetching the schemas to be validated from the filesystem
(ie. the checked-out repo).
> Add util function to to read schema from a file

- src/schematools/contrib/django/factories.py
- src/schematools/contrib/django/models.py
- src/schematools/types.py
Also rewrote how additional_relations is parsed and used for reverse relations
Relations can be resolved now thanks to the DatasetCollection. This removes the need for parsing code that resolves relations, as the schema types can now provide this information:
* Added `field.related_table`
* Added `field.reverse_relation`
* Added `table.get_reverse_relation()`
* Replaced `table.relations` -> `table.additional_relations` which returns a Python object instead of raw schema dict data.
> Hide the reverse relation for unmentioned M2M relations

- src/schematools/permissions/auth.py
If a profileschema gives dataset wide permissions and no table-level
permissions a 500 was returned because of a logic error.
> AD#21442 Bugfix profile with dataset wide permission works

- src/schematools/types.py
This allows both AdditionalRelationSchema and DatasetFieldSchema based relations to be accessed in the same way.
> Make sure AdditionalRelationSchema has the same relational properties

- src/schematools/importer/base.py
- tests/test_rowclass.py
When the `id` field in incoming data is used in a provenance,
special care needs to be taken because in some situations
an `id` field is autogenerated to provide the singular PK value
that Django needs.
So, the original value needs to be retained (it would otherwise
be overwritten with the generated `id` field).
And, when asking for the provenanced field, the provenancing
mechanism should *not* to be applied.
So, in this example, the schema fragment is:
"neuronId": {
"type": "string",
"provenance": "id"
}
The incoming json contains an `id` field that need to become
available as `neuronId`.
Without precautions, the autogenerated `id`, e.g. having a value
of "012.5" would be put in the place of the `neuronId` field
and the original value would be lost.
> Add special case to rowclass for provenance with `id` field

- src/schematools/importer/ndjson.py
- src/schematools/types.py
The implementation of `field.sub_fields` was adding prefixes
to fieldnames. These prefixes are for a special use-case,
where the `sub_fields` method is used to generate extra fields
describing the components of a compound foreign key.
However, adding these prefixes should not be the default behaviour of `sub_fields`.
This has been fixed. The property fields `sub_fields`
has now been converted into a function `get_sub_fields`
with an extra parameter `add_prefixes`.
The property `sub_fields` is still available and implements
the default use-case, generating fields without prefixes.
> AB#20011 Change `field.sub_fields` to not add prefixes

- src/schematools/contrib/django/factories.py
- src/schematools/contrib/django/models.py
Sometimes I found during the fixing of temporality-listings. The loose relations M2M field doesn't really do anything loose at all. I guess the relations are created at import?
The constructor receives a 'relation' argument and 'max_length' but these are not used or don't do anything different from standard Django. The same goes for `LooseRelationManyToManyField`, which didn't do anything with the provided max_length. And the 'related_model' was not used at all either.
> Decouple LooseRelationField from schema's. Pass a to_field instead.

- src/schematools/events/export.py
- src/schematools/events/full.py
- src/schematools/importer/ndjson.py
- src/schematools/types.py
This is the proper spelling.
More importantly, I wanted to change the semantics of the method and property, and renaming it seemed the easiest option to break any code that relied on the old behavior and force reconsideration.
The new method and property return an empty iterator/list for an array or object instead of raising a `ValueError`. A use site in DSO-API caught the `ValueError`, but as a result also caught unrelated errors, causing a bug in production and tests successes where failures were appropriate (Amsterdam/dso-api#402). It looks like the only other call site performs a custom type check and should not be affected.
> Replace DatasetFieldSchema.sub_fields by subfields

- src/schematools/types.py
- tests/conftest.py
- tests/files/compound_key.json
- tests/test_types.py
`get_fields()` now returns `id` twice for for example the verblijfsobjecten dataset
> Only return surrogate pk for schemas with compound pk if schema does not define `id`

- pyproject.toml
- setup.cfg
- src/schematools/__init__.py
- src/schematools/factories.py
The method tables_factory retrieves database schema if defined as a parameter when creating a database table. If schema is None, it now defaults to Public. Leave it to None will have a risk that the DB schema that is currently in use will be used to create the table in leading to unwanted/unexepected results.
> explicit database schema default when None

- src/schematools/types.py
Additional filters have been replaced by temporal ones.
I wanted to remove these in 3.0, but didn't have the required DSO-API changes ready. For 4.0, then.
> AB#24402 Deprecate methods dealing with additionalFilters

- src/schematools/__init__.py
- src/schematools/importer/base.py
Because schemas needed to be made always explicit (to avoid using wrong
db schema), the index creation was broken.
Now the db schema for index creation is also made alway-explicit.
[And fixed some type constants]
> Fix index creation because of always explicit schemas

- src/schematools/cli.py
Was:
Usage: schema validate [OPTIONS] DATASET_ID META_SCHEMA_URL
Validate a JSON file against the amsterdam schema meta schema.
Args:     schema_url: url where schema can be found.     dataset_id: id of
the dataset.     additional_schemas: Schemas that should be preloaded.
meta_schema_url: is the url where the metaschema         for amsterdam
schema definitions can be found.
Now:
Usage: schema validate [OPTIONS] DATASET_ID META_SCHEMA_URL
Validate a schema against the Amsterdam Schema meta schema.
Args:
DATASET_ID: id of the dataset.
META_SCHEMA_URL: url where the metaschema for Amsterdam Schema
definitions can be found.
In both cases, options follow, and those get descriptions from `click.option`/`click.argument`.
> Fix usage text for "schema validate"

- src/schematools/permissions/db.py
When a `dataset.id` has capital letters (camelcase)
the GRANT statement has a wrong tablename.
This commit fixed that by applying a `to_snake_case`
on the `dataset.id` so that GRANTS can be applied correctly.
> AB#24662 Generate correct tablename in grants

- Dockerfile
- src/schematools/types.py
- tests/django/test_models.py
Since we are only pointing to the primary identifier of the target relation, we only need that FK in the through table.
> Avoid adding compound keys to through table when relation is loose

- src/schematools/types.py
Also note that `has_shortname` shouldn't really be used. Applications should just get the name.
> Clarify id vs. name in DatasetFieldSchema docstrings

- pyproject.toml
- setup.cfg
- src/schematools/contrib/django/factories.py
- src/schematools/importer/__init__.py
- src/schematools/types.py
Does what @gkoller intended, without breaking the other changes from #239. Can check later whether the attribute naming should be improved.
> Revert changes to fix broken _parent_schema field.

- src/schematools/factories.py
These table ids are used to compare with incoming arguments
that are in snake_case. We already decided that a refactoring
is needed to determine the interfaces where case "flips" are needed,
but thats for another (and much bigger) user-story.
> For through tables in table factory comparisons need snake casing

- src/schematools/types.py
In the datasets_datasettable table in the `db_table` column the
dataset part of the table name was not being snake_cased.
> AB#28214 Fix snakecase bug in datasettable

- README.md
- pyproject.toml
- setup.cfg
tbump wants to push to master on GH, which we don't allow anymore.
Replace it by instructions for doing a release.
> Drop tbump

- src/schematools/cli.py
- src/schematools/validation.py
- tests/test_validation.py
All decorators were stateless classes with a single validate method that
were attached to their base class. This made writing new validators a
pain because of all the boilerplate and the flake8 requirement of having
a docstring both on the class and on the validate method.
The new code uses ordinary standalone functions with a decorator to
register them as validators. They're now also all marked as private with
the familiar underscore, and they have a human-readable name that is
independent of their identifier.
> Rewrite schema validators as decorated functions

- setup.cfg
- src/schematools/factories.py
The `dataset id` is used for defining the database schema where the tables of that dataset will reaside. In some cases the dataset id is camelCased. Leading to also the prefix of tables - that contain the name of its schema - to have camelCased prefixes. Which leads to wrong table names and issues for the datateams. To cope with this, the dataset id is snaked cased.
> [FIX] camelCase in dataset id

- docker-compose.yml
- src/schematools/permissions/db.py
- tests/conftest.py
- tests/files/data/hr_auth.ndjson
- tests/files/hr_auth.json
- tests/test_permissions.py
While implementing this, I noticed that the exception handler inside the SQL statement was silently swallowing errors whenever we try to run a GRANT on a non-existing field or table. Removing this revealed two other bugs:
1) applying permissions to FK fields doesnt work because the name used to apply the perm does not include the `_id` suffix
2) snakecasing dataset ids breaks the command because dataset ids are imported with their raw id (i.e. unsnakecased)
The first problem is now explicitly omitted with a FIXME and ive added a [ticket](https://dev.azure.com/CloudCompetenceCenter/Data%20Diensten/_backlogs/backlog/Data%20Diensten%20Team/Stories/?workitem=28436)
The second problem has been solved by #249
> AB#27817 Consider shortnames when applying table perms

- README.md
The list of schema subcommands was out of date. Refer the user to --help
for the current list, so we don't have to maintain it in the README.
The PostgreSQL requirement is now explicitly stated.
Describe how schemas are (usually) loaded. Having a single file with a
dataset schema is not enough for some (most?) commands.
> Update schema command description in README.md

- src/schematools/importer/base.py
"Created schema" is ambiguous in the context of a package that works with JSON Schemas and SQL SCHEMAS.
> Fix confusing log message from "schema create tables"

- src/schematools/cli.py
- src/schematools/datasetcollection.py
- src/schematools/exceptions.py
- src/schematools/loaders.py
- src/schematools/utils.py
The configurable schemaloader could only be used for loading
individual datasets. It now has been expanded to also
support loading all datasets using the schemaloader.
So, it is now possible to load all dataset from the filesystem.
(Rant could be removed from the comments :-)
> AB#26860 Use schemaloader for loading of all datasets

- src/schematools/types.py
- tests/test_types.py
The name of this method matches that of the one on DatasetTableSchema, rather than those of the other DatasetFieldSchema methods (`get_subfields` etc.). That's on purpose: the filter validation in DSO-API assumes it can use the same method on both types to walk a schema and resolve a compound field name.
> [AB#24838] Add get_field_by_id to DatasetFieldSchema

- setup.cfg
- src/schematools/contrib/django/factories.py
- src/schematools/contrib/django/management/commands/create_tables.py
- src/schematools/types.py
- tests/django/conftest.py
- tests/django/test_models.py
- tests/files/afval.json
This is already being done for the SQLAlchemy based commands.
This functionality to add comments to the database is missing from the Django ORM. This is a long-standing feature request. However, there is an Django plugin `django-db-comments` that adds this functionality.
Unfortunately, this does not work out-of-the-box for our situation, where Django models are generated on-the-fly.
In this PR the plugin is used as far a possible.
> AB#28930 add titles for table and fields to the database as extra comments

- src/schematools/permissions/auth.py
- src/schematools/types.py
First step toward closed-by-default with explicit marking of public data sets, [AB#40314](https://dev.azure.com/CloudCompetenceCenter/089b38ee-0066-4b66-a36c-20744a0e4348/_workitems/edit/40314).
This special scope is defined by the Amsterdam Schema spec, so it makes sense to handle it entirely in schema-tools rather than DSO-API.
The string constant is now repeated in several modules, because defining it centrally in permissions.auth causes a circular import (even when in a submodule permissions.auth._public). Leaving that problem for later, when we implement closed-by-default logic.
All DSO-API tests pass with this PR applied, except some index views that now display `["OPENBAAR"]` where they previously displayed `[]` or `None`. In the long run, that's what we want anyway, so I'll fix …
> Recognize the implicit scope "OPENBAAR"

- .pre-commit-config.yaml
- src/schematools/importer/ndjson.py
- tests/files/data/hr_auth.ndjson
- tests/files/data/hr_sbi_act_nr.ndjson
- tests/files/hr.json
- tests/test_ndjson.py
When a table identifier in an amsterdam schema definition
does have a shortname, the ndjson import is failing.
This commit fixes this behaviour by modifying incoming
records for those shortnamed identifiers.
The idea is that in the incoming ndjson the identifiers
that are used are always according to the amsterdam schema.
The shortname is a implementation detail, that should only
be used at the moment that records are prepared for
insertion into the sql database.
> AB#28435 Fix shortnamed identifiers for ndjson import

- tests/test_validation.py
Lazy fix: test specific validations where other validations would bork on a dataset. The test files have become a bit of a tangle.
> Fix validation tests

- src/schematools/permissions/db.py
This too was broken by the `scopes=[]` -> `scopes={"OPENBAAR"}` change.
> Fix permissions.db

- Dockerfile
- docker-compose.yml
- src/schematools/contrib/django/factories.py
- tests/django/test_models.py
fixes [AB#38356](https://dev.azure.com/CloudCompetenceCenter/089b38ee-0066-4b66-a36c-20744a0e4348/_workitems/edit/38356)
This will only work for newly imported tables. In order to apply this to existing datasets, they need to be dropped and re-imported.
> CheckConstraint for non-composite string identifiers enforcing absence of slashes

- src/schematools/contrib/django/factories.py
- src/schematools/contrib/django/management/commands/create_tables.py
- tests/django/test_models.py
- tests/files/afval.json
This reverts commit b4dcf8983dc6bbf2c66ed8d76039847cbbebeda6 as a hotfix for [AB#44268](https://dev.azure.com/CloudCompetenceCenter/089b38ee-0066-4b66-a36c-20744a0e4348/_workitems/edit/44268). import_schemas --create-tables fails on an id column that does not exist. I cannot reproduce this locally as I hit a different bug earlier in the process:
django.core.exceptions.FieldError: Cannot resolve keyword 'sbiActiviteitNummer' into field...
Skipping this doesn't do much as many datasets have this issue. No idea what's going wrong here.
> Revert "Intergrate django-db-comments into `create_tables` mgm. command"

- .pre-commit-config.yaml
- src/schematools/factories.py
- src/schematools/maps/interfaces/mapfile/serializers.py
- src/schematools/types.py
- src/schematools/validation.py
For [AB#46681](https://dev.azure.com/CloudCompetenceCenter/089b38ee-0066-4b66-a36c-20744a0e4348/_workitems/edit/46681). Also fixed some errors that it found and added a "nosec" annotation to the final one: a jinja2.Environment was created with HTML/XML autoescaping off. We're not generating XML here, though.
> Add bandit security linter to pre-commit hooks

- setup.cfg
- src/schematools/contrib/django/factories.py
- tests/django/test_models.py
The check constraint for slashes in ids is not unique
over the datasets. Django checks borks on this.
> Make name of the check constraint more specific

- setup.cfg
- src/schematools/cli.py
- src/schematools/permissions/db.py
- tests/test_permissions.py
On Azure, not every schema has an associated PostgreSQL table. The `schema permissions apply` was crashing on this.
Now, the code is catching these exceptions and only issues a warning (a Notice from PostgreSQL).
Furthermore, the cli command is now less chatty by default.
> AB#39233 permissions revoke error

- setup.cfg
- src/schematools/permissions/db.py
De pre-commit run op amsterdam-schema geeft nu een:
`TypeError: 'type' object is not subscriptable`
Dit zou dat moeten fixen
> Fixed type hinting for get_all_dataset_scopes

- src/schematools/validation.py
- tests/test_validation.py
Validator now checks whether 'mainGeometry' exists
in tables that have fields of type geometry
but no field named 'geometry'
> Validate mainGeometry exists where required

- src/schematools/validation.py
- tests/files/rel_auth.json
- tests/test_validation.py
The new rule is that the auth scopes on a relation field (including those inherited from dataset and table) should be a superset of the scopes on the field to which the relation field points.
[AB#40393](https://dev.azure.com/CloudCompetenceCenter/089b38ee-0066-4b66-a36c-20744a0e4348/_workitems/edit/40393)
> Validate auth on relations according to new rule

- src/schematools/cli.py
- src/schematools/contrib/django/app_config.py
- src/schematools/contrib/django/factories.py
- src/schematools/contrib/django/management/commands/dump_models.py
- src/schematools/contrib/django/models.py
- src/schematools/datasetcollection.py
- src/schematools/events/consumer.py
- src/schematools/events/export.py
- src/schematools/events/full.py
- src/schematools/factories.py
- src/schematools/importer/base.py
- src/schematools/importer/ndjson.py
- src/schematools/loaders.py
- src/schematools/maps/interfaces/json_.py
- src/schematools/permissions/auth.py
- src/schematools/permissions/db.py
- src/schematools/types.py
- src/schematools/utils.py
- src/schematools/validation.py
- tests/conftest.py
- tests/django/fixtures.py
- tests/django/test_models.py
- tests/test_permissions.py
- tests/test_permissions_auth.py
- tests/test_types.py
pyupgrade --py38-plus already suggests to use the Python 3.9 format if the type annotations use a 'from __future__' construct that avoids actual code execution.
> Upgrade type annotations to modern Python format

- src/schematools/permissions/auth.py
For structured logging, primarily. This way, we can do `json.dumps(list(request.user_scopes))` etc.
Also removed the docstring on __str__ that flake8 complained about.
> Add an __iter__ to UserScopes

- .pre-commit-config.yaml
- src/schematools/factories.py
-1 to_snake_case.
I had to remove the python_version from the pre-commit config to make it work with my Python 3.10.
> Use db_name in factories instead of reimplementing it

- setup.cfg
- src/schematools/cli.py
- src/schematools/contrib/django/models.py
- src/schematools/importer/base.py
- src/schematools/types.py
- src/schematools/utils.py
- tests/conftest.py
None of this was used in DSO-API or dataservices-airflow. `get_fk_fields` was used internally, so it's now a private method. It also returns `[DatasetFieldSchema]` instead of `[str]` to be more generally useful and to allow reuse of the `db_name` method (-1 `to_snake_case`!). `schema_fetch_url_file` was moved to its only spot of use and made private, with the previous deprecation method as a comment.
> Remove deprecated and unused code

- src/schematools/contrib/django/factories.py
- src/schematools/contrib/django/models.py
- src/schematools/permissions/auth.py
- src/schematools/types.py
This changes the LooseRelationField into an actual foreign key, so applications can perform joins on the relation. This change is backwards incompatible, and DSO-API will have an corresponding PR to be compatible with this change.
This only affects the fields that are *not* part of a composite foreign key. Those remain simple charfields.
> AB#50108: Convert LooseRelationField into an actual relation

- src/schematools/importer/ndjson.py
- tests/test_ndjson.py
In case of a nm relation the data doesn't need to be there, but in an other table. Don't try to rename if the data is not there.
> Fix importing for fields with shortname and no data

- src/schematools/validation.py
- tests/files/schema_ref_validation.json
- tests/test_validation.py
Hostname in `properties/schema` should always be:
`schemas.data.amsterdam.nl`. The path part of the `$ref`
is already being checked in the structural validation.
> AB#52532 Add validator to check hostname in `$ref`

- setup.cfg
- src/schematools/contrib/django/management/commands/change_dataset.py
The reason to allow this combination is to generate OpenAPI docs for the remotes. We generate those with drf_spectacular, which looks at the database. Generating OpenAPI docs from the schemas directly would be possible, but only by duplicating all of drf_spectacular's functionality.
For [AB#50780](https://dev.azure.com/CloudCompetenceCenter/089b38ee-0066-4b66-a36c-20744a0e4348/_workitems/edit/50780).
> Allow enable_db with an endpoint_url

- setup.cfg
- src/schematools/validation.py
- tests/files/id_type.json
- tests/test_validation.py
For [AB#53421](https://dev.azure.com/CloudCompetenceCenter/089b38ee-0066-4b66-a36c-20744a0e4348/_workitems/edit/53421).
I had to change an unrelated map expression to a comprehension to make flake8 happy.
> Add validator for the types of identifier fields

- src/schematools/contrib/django/management/commands/change_dataset.py
This reverts commit 2a9bbab25d2ed9004b046c7ff48d8a42acc9845a.
Reason: unforeseen side-effects of enable_db with some remotes.
> Revert "Allow enable_db with an endpoint_url (#320)"

- setup.cfg
- src/schematools/contrib/django/factories.py
That practice also hinders security patches in the future.
> Avoid dependency restrictions that break project upgrades

- src/schematools/cli.py
These command have not been used for a long time and were lacking a table_id argument.
> Fix ndjson/geojson cli import command

- src/schematools/ckan/_convert.py
- src/schematools/cli.py
- src/schematools/contrib/django/management/commands/import_profiles.py
- src/schematools/contrib/django/management/commands/import_schemas.py
- src/schematools/loaders.py
- src/schematools/utils.py
- tests/test_ckan.py
Fixes [AB#59480](https://dev.azure.com/CloudCompetenceCenter/089b38ee-0066-4b66-a36c-20744a0e4348/_workitems/edit/59480): dataset schema loaders now return the paths as the keys in their dicts, instead of duplicating the id's (which are already present in the `DatasetSchema` objects). This allows us to easily produce the right paths in the CKAN exporter, it saves a round-trip to `schemas.data` in `dataset_paths_from_url` and I also need this for the DSO-API docs rewrite.
Still todo: update current DSO-API docs generation to the new semantics of `dataset_schema_from_(path|url)`.
> Have schema loaders returns dataset paths

- tests/conftest.py
- tests/django/conftest.py
- tests/django/test_models.py
This way, pytest will run the tests that it can without a database, so we can set up continuous testing (#331).
The implementation is very ugly, but I couldn't boil it down further. The pytest-django plugin doesn't have good support for skipping, so we need to stop collecting the tests instead of skipping them. This gives misleading output, in the sense that the skipped tests aren't even reported as such.
> Skip tests that require the database if not configured

- tests/django/test_models.py
If not, pytest considers it an error.
> Make `reason` for pytest.mark.skipif a keyword argument

- src/schematools/contrib/django/factories.py
- src/schematools/contrib/django/management/commands/import_schemas.py
- src/schematools/contrib/django/models.py
- src/schematools/events/export.py
- src/schematools/events/full.py
- src/schematools/factories.py
- src/schematools/introspect/db.py
- src/schematools/naming.py
- src/schematools/types.py
- src/schematools/utils.py
- src/schematools/validation.py
- tests/django/test_mocking.py
- tests/test_utils.py
Triggered by circular import exceptions that occur when utils is imported before typing (but not the other way around). Having a utils module is a code smell anyway.
This replaces #341.
> Split naming module off of utils

- src/schematools/loaders.py
> Allow get_schema_loader() without arguments, avoid breaking an empty env var

- src/schematools/importer/base.py
- src/schematools/importer/geojson.py
- src/schematools/importer/ndjson.py
- tests/test_import.py
This allows projects like dataservices-airflow to track the "cursor" field in the BenK/GOB data import. That field is not part of the schema, but needed to retrieve more data. As a side effect, the typing in code became much easier to read, and debugging shows source data too.
> Bundle 'source' data to imported records for debugging and field tracking

- CHANGES.md
- setup.cfg
- src/schematools/factories.py
- tests/test_ndjson.py
This is done for consistency as `get_table_by_id()` also accepts the old snake-cased identifiers.
Otherwise, the parameters of `BaseImporter.generate_db_objects()` allow snake-cased ID's for `table_id` but need the exact ID's for `limit_tables_to`.
> Restore ability to use snake-cased table ID's in limit_tables_to.

- src/schematools/cli.py
I still haven't found what "not available" is called on data.overheid.nl, or if there even is a status value that expresses it. Looks like omitting the availability field is interpreted as available, so just don't upload datasets marked "not available".
> CKAN: Skip datasets that are "niet_beschikbaar"

- src/schematools/contrib/django/factories.py
- src/schematools/types.py
This removes the complex `FieldMaker`/`RelationMaker` inheritance logic, and replaces them with plain Python functions.
This also accidentally fixes a bug with geometry fields. Because `JSON_TYPE_TO_DJANGO` has a a static kwargs argument for those, it would be directly altered by the `FieldMaker` - and therefore the next could field receive the `verbose_name` of the previous last geometry field that had one.
> Cleanup and simplify model field factory logic

- src/schematools/contrib/django/management/commands/import_schemas.py
- src/schematools/loaders.py
This fixes cases like: `./manage.py import_schemas ../../amsterdam-schema/datasets/bag/dataset.json`
> Fix relative path import for schema files

- src/schematools/contrib/django/models.py
- src/schematools/exceptions.py
- src/schematools/loaders.py
- src/schematools/types.py
All derive from `SchemaObjectNotFound` now, removing the need to catch multiple exception types. There are also distinct exception types when a dataset/table/field is not found - in case the caller needs that.
> Normalize schematools exceptions for DatasetNotFound/SchemaObjectNotFound

- CHANGES.md
- src/schematools/validation.py
- tests/files/datasets/idcomposite.json
- tests/test_validation.py
Checks for the issue that 'brk' previously had, where the identifier got overwritten inside the NDJSON importer.
Also removed unused bits from validation.py.
> Add validator for 'id' field with composite key

- src/schematools/importer/ndjson.py
- tests/files/data/kadastraleobjecten.ndjson
- tests/files/datasets/kadastraleobjecten.json
- tests/test_ndjson.py
When the data contains an `id` during import, its processed twice. Its safe to skip the second iteration.
> Fix processing `id` field twice

- .github/workflows/test.yaml
As promised in c4917bfbd70aaa3b7f898aab57103cd41ed7bb8b. Since that commit, tests that do not require a database are skipped.
> Add GitHub workflow to run tests

- src/schematools/contrib/django/apps.py
- src/schematools/contrib/django/factories.py
- src/schematools/types.py
- tests/conftest.py
- tests/django/fixtures.py
- tests/django/test_models.py
- tests/files/datasets/aardgasverbruik.json
This makes sure the field is 'tagged' as OneToOneField, and has all database features that come with that field class. The actual model lookup is purposefully disabled, so accessing the field will still return the raw db_column value. Otherwise, Django would query the related table to retrieve the value.
> Support primary keys that also have a relation

- src/schematools/types.py
This method gives access to the "identifier" property on datasets. While some datasets have that, it is not in line with the Schema spec and never used. When I replace the property definition by
@property
def identifier(self) -> str:
raise ValueError("crash")
the tests for schema-tools and DSO-API all still run.
> Remove unused property DatasetSchema.identifier

- src/schematools/contrib/django/factories.py
- src/schematools/contrib/django/management/commands/sqlmigrate_schema.py
This builds a ProjectState for the old and new table, allowing the migration engine to generate the proper set of operations.
> Add sqlmigrate_schema management command to generate migration SQL

- src/schematools/__init__.py
- src/schematools/cli.py
- src/schematools/exceptions.py
- src/schematools/types.py
- src/schematools/validation.py
- tests/test_validation.py
* Schematools now defines which metaschemas it can work with and restricts its usage to these versions
* The validation logic is updated to support validation attempts on multiple metaschema versions so we can transition datasets from one major version to another in amsterdam-schema
* `DatasetTableSchema.validate` and `DatasetTableSchema._resolve` have been removed because they are remnants of an abandoned atempt to make datase-schema an table-schema compliant JSON schemas
> Metaschema aware schematools

- .pre-commit-hooks.yaml
- src/schematools/cli.py
* main feature in the title
* fixed a bug in batch_validate which assumed the presence of an optional argument
This has been tested on amsterdam-schema by using a local reference to the schematools repository in the pre commit hook config
> Publisher validation precommit hook

- src/schematools/cli.py
GH actions trims lines to a maximum length. This ensures that *some* of the errors are now readable.
> schema batch-validate: print errors on separate lines

- CHANGES.md
- setup.cfg
- src/schematools/cli.py
`jsonschema.ValidationError.message` is much less informative than its `__str__`. The former is also squashed into a single line that gets trimmed down by GitHub Actions so that only a part of the schema JSON appears in the UI.
> Better error messages from schema batch-validate

- src/schematools/contrib/django/factories.py
- src/schematools/contrib/django/faker/__init__.py
- src/schematools/factories.py
- src/schematools/importer/ndjson.py
- src/schematools/types.py
- tests/django/test_mocking.py
- tests/django/test_models.py
- tests/files/data/kadastraleobjecten.ndjson
- tests/files/datasets/kadastraleobjecten.json
- tests/test_ndjson.py
Objects fields that are not a relation are now 'flattened' to fit in the relational database. So, a schema definition with the following field:
```
"naamGebruik": {
"type": "object",
"properties": {
"code": {
"type": "string"
},
"omschrijving": {
"type": "string"
}
}
}
```
will generate a Django model that has fields `naam_gebruik_code` and `naam_gebruik_omschrijving`.
Furthermore, a json type field has been added, so the following field:
```
"soortGrootte": {
"type": "object",
"format": "json"
}
```
will generate a jsonb field in the Postgres database.
NB. the structure of this json field is not validated! So, the only check is that the postgres database ensures that the data can be parsed as json.
Also the mocker has been updated to correctly supply these object fields with fake data. …
> AB#61561 Support object fields in amsterdam schema

- src/schematools/contrib/django/__init__.py
This is no longer needed as of [Django 3.2](https://docs.djangoproject.com/en/3.2/ref/applications/#for-application-authors). Removes the only deprecation warning given by
python -Wa src/manage.py test
in DSO-API.
> Remove schematools.contrib.django.default_app_config

- CHANGES.md
- setup.cfg
- src/schematools/cli.py
- src/schematools/validation.py
This is a regression that was introduced when we added functionality to support validating schemafiles that are tables, because `validation.run` implicitly assumed that the passed location was always the dataset file location
> Fix semantic validator that assures dataset id is identical to dataset file directory

- src/schematools/cli.py
Apparently, the path in a jsonschema.ValidationError can contain any types, as seen in the TypeError at
https://github.com/Amsterdam/amsterdam-schema/actions/runs/4045114336/jobs/6956149861
Just print it in Python syntax. We'll figure it out.
> Print error path as is from batch-validate

- CHANGES.md
- setup.cfg
- src/schematools/cli.py
The metaschema enforces a $ref in the publishers reference but the json we hold against it is inlining them. Not so good.
> Patch release 5.6.9: Dont inline publishers in structural validation

- CHANGES.md
- setup.cfg
The next version (1.13.0) requires  sqlalchemy >=1.4.0 Where we require sqlalchemy < 1.4.0
> Pin GeoAlchemy2 to 1.12.5

- src/schematools/types.py
- tests/test_types.py
I just got a "maximum recursion depth exceeded" error from a broken schema. The issue is that exceptions use its __repr__, which calls qualified_id, which looks up the 'id', which causes a trap to __missing__, which again calls __repr__. This cycle is now broken.
> Fix repr of SchemaType in case of missing keys

- CHANGES.md
- src/schematools/cli.py
- src/schematools/types.py
- tests/test_types.py
* When no META_SCHEMA_URL was given, schema validate reported invalid against all metaschemas.
* A schema that was invalid for one version was reported as invalid for all versions.
* schema validate was inconsistent with batch-validate because of differing inline_publishers settings.
For [AB#68513](https://dev.azure.com/CloudCompetenceCenter/089b38ee-0066-4b66-a36c-20744a0e4348/_workitems/edit/68513).
> Fix schema validate

- CHANGES.md
- src/schematools/contrib/django/models.py
- tests/django/test_models_profile.py
Fixes [AB#48793](https://dev.azure.com/CloudCompetenceCenter/089b38ee-0066-4b66-a36c-20744a0e4348/_workitems/edit/48793): importing profiles did not work.
Also fixed the formatting of the changelog.
> Store profiles as JSON

- CHANGES.md
- src/schematools/validation.py
- tests/files/datasets/enum_types.json
- tests/test_validation.py
From now on, enums are only allowed with types string and integer. The schema spec has no rule for this, so we could allow object enums in theory, but I'm not sure those are actually implemented. Change this if someone does want an object enum.
Fixes [AB#52842](https://dev.azure.com/CloudCompetenceCenter/089b38ee-0066-4b66-a36c-20744a0e4348/_workitems/edit/52842).
> Validate enum types in schemas

- CHANGES.md
- setup.cfg
- src/schematools/types.py
Authorisation on these fields was implemented by setting an "auth" with the union of table and field scopes on the synthetic table schema for the field's database table. That means that having any of these scopes, rather than at least one of the table scopes and one of the field scopes, allowed access to the array field.
The field scopes are now set on the synthetic parent field's "auth", which is what DSO-API checks when looking for fields to omit.
> Fix authorisation on array fields

- src/schematools/importer/ndjson.py
- src/schematools/types.py
- tests/files/data/brk_aantek_rechten.ndjson
- tests/files/datasets/brk.json
- tests/files/datasets/gebieden.json
- tests/files/datasets/hr.json
- tests/test_ndjson.py
- tests/test_types.py
For the BenK datasets relations can have their own "geldigheid". To store this extra information, a through table is needed.
This is already in place for NM relations and for
1-N relations having a temporal table as the target.
However, for 1-N relations to a non-temporal table no through table is being created.
The condition that was in place to determine if a 1-N relation needs a through table was based on the temporality of the target. This condition has been changed now. The new condition is as follows. If the relation does contains fields that are not part of the key a through table will be defined for this relation.
An example:
The table `brk.tenaamstelling` has the following 1-N relation field:
"isGebaseerdOpStukdeel": {
"type": "object",
"properties": {
"identificatie": {
"type": …
> Fix code to enable attributes on a relation

- CHANGES.md
- setup.cfg
- src/schematools/events/full.py
Because schematools is used from Airflow and the
current Airflow needs SA >= 1.4
Also bumped geoalchemy2 and unpinned pg-grant.
Bumping SQ to >= 2.0 creates a lot of imcompatibilities, so let's stick with < 2.0 for now.
> Pin SQLAlchemy to >=1.4, < 2.0

- CHANGES.md
- setup.cfg
- src/schematools/types.py
The condition that determines if 1-N relation gets a through tables was change to only depend on the fact if the relation has extra fields.
However, for a 1-N relation to a temporary table *without* extra field, we still need to have a through table, so the code has been changed occordingly.
> Fix condition for 1-N through tables.

- CHANGES.md
- setup.cfg
- src/schematools/exports/__init__.py
Export is now crashing for nested fields,
because the sql that is generated for ogr2ogr contains fields that are not part of the table.
> Exclude all array fields for exports

- CHANGES.md
- setup.cfg
- src/schematools/cli.py
- src/schematools/introspect/db.py
- src/schematools/introspect/utils.py
- tests/test_geojson.py
- Validate now shows an error message when context info is absent.
- Show camelCased ids for datasets
- Fix template for generating amsterdam schema by introspecting a pg table.
> Some small schematools fixes, needed for cli demo

- setup.cfg
- src/schematools/importer/ndjson.py
The format is so trivial that we don't need a library for it. Using orjson should also be faster, though I haven't bothered to benchmark.
> Parse NDJSON using orjson

- setup.cfg
- src/schematools/cli.py
- tests/test_ckan.py
This package has no license, copyright or homepage on PyPI, and hasn't been updated since 2016. I'm not sure why we're using it at all.
> Remove json_encoder dependency

- setup.cfg
- src/schematools/contrib/django/factories.py
- src/schematools/contrib/django/fields.py
- src/schematools/contrib/django/management/commands/dump_models.py
- tests/django/test_models.py
... because django_postgres_unlimited_varchar has no license, so it's unclear what we can use it for.
> Replace UnlimitedCharField with our own implementation

- CHANGES.md
- setup.cfg
- src/schematools/importer/base.py
This functionality has not been fully completed yet. And the decision still has to be made how to continue with versioning. So, for now we disable this functionality,
because the event processor cannot work at the moment.
> Disable versioning that creates postgres schemas for new tables.

- CHANGES.md
- setup.cfg
- src/schematools/cli.py
The `schema show dataset` and `schema show datasettable` cli function get a flag `--to-snake-case` for convenience in bash scripting.
> Add --to-snake-case flag to cli functions

- src/schematools/events/full.py
- src/schematools/importer/base.py
Caused a huge overhead, while the pk lookup table is never used when processing events. Added a parameter to just skip the creation of the pk lookup table, only for this use case.
> Skip creation of pk_lookup table when importing from events

- setup.cfg
- src/schematools/cli.py
- src/schematools/exports/csv.py
- src/schematools/exports/geopackage.py
- src/schematools/exports/jsonlines.py
The SQLAlchemy `execute` is loading a full set of records in memory, leading to 4Gb of mem consumption for large datasettables like brk.kadatastraleobjecten.
The new SA 1.4 that we are using already has a nice streaming/batching mechanisme to reduce this memory consumption.
The SA engine has been changed now to be able to use the new connection. No failing tests, so it seems this change is backwards compatible.
> Make export to csv/jsonlines less memory hungy

- CHANGES.md
- setup.cfg
- src/schematools/contrib/django/factories.py
- src/schematools/contrib/django/faker/__init__.py
- src/schematools/naming.py
- tests/django/test_model_mockers.py
- tests/django/test_models.py
- tests/files/datasets/afval.json
- tests/test_naming.py
The mocker factory logic is passing a DatasetTableSchema object with stripped down relation fields and the camel-cased db_name as identifiers for fields. This goes wrong when an identifier x passed to `to_snake_case(toCamelCase(x))` does not produce x. Which is the case for "eersteHNId". Since capital letters should be recognized as a word boundary, Ive expanded the definition of the camel case word boundary regex to include capital letters in between other capital letters.
This would have fixed the original problem with the mangled DatasetTableSchema passed to model_mocker_factory but it seemed a bit weird to me to implicitly rely on toCamelCase and to_snake_case being invertible. Ive therefore chosen to explicitly mangle the DatasetTableSchema fields with the db_name and document it. 
I …
> Model mocker field naming 

- src/schematools/events/full.py
- tests/test_events_full.py
This new logic makes sure that when a message is redelivered, we can recover from it and the database state after having processed the redelivered message would be the same as if the message would have been processed correctly the first time.
> Implement logic to recover from failed event messages

- CHANGES.md
- setup.cfg
- src/schematools/events/full.py
- src/schematools/factories.py
- src/schematools/importer/base.py
- src/schematools/types.py
Two bugfixes:
- Replace use of engine.execute() in BaseImporter with engine.connect() - not supported anymore in SQLAlchemy 1.4
- Use column names in INSERT INTO statement instead of column positions.
> Two bugfixes: Don't use engine.execute() anymore and use column names instead of column positions in INSERT INTO query

- CHANGES.md
- setup.cfg
- src/schematools/contrib/django/faker/__init__.py
- src/schematools/contrib/django/faker/create.py
- src/schematools/contrib/django/management/commands/create_mock_data.py
And fix a bug in nullable_int combined with enum.
> Add a option to mocking to process only a subset of the tables

- CHANGES.md
- setup.cfg
- src/schematools/cli.py
- src/schematools/permissions/db.py
- tests/test_permissions.py
in the format `<table_name>:<privilege_1>[,<privilege_n>]*;<grantee_1>[,grantee_n]*`.
Be aware that this is not completely fool-proof. If not-existing tables/prvilege/grantees are used, the script will bail out.
This options has mainly been added for Azure, where acces to the internal dataset_* tables (used by Django) is done in the context of a user (or the anonymous user) and the `scope_openbaar` grant is needed for these internal tables.
Grants can be added using a `--additional-grants` flag
> AB#91240 Add extra option to permissions cli to add additional grants

- CHANGES.md
- setup.cfg
- src/schematools/exports/__init__.py
- src/schematools/exports/csv.py
- src/schematools/exports/jsonlines.py
The bag_panden table had a historical record with a year of 0001. The dbapi.fetchmany function cannot handle this year, so we need a way to circumvent this problem. Luckily, in psycopg2 we are able to define custom handlers for specific column types. So, we convert datetimes to string, which is done anyway during the export.
> AB#92275 Circumvent wrong date in bag_panden during export

- CHANGES.md
- setup.cfg
- src/schematools/contrib/django/management/commands/sqlmigrate_schema.py
- src/schematools/loaders.py
> SQL migrate improved

- CHANGES.md
- setup.cfg
- src/schematools/permissions/auth.py
- tests/conftest.py
- tests/test_permissions_auth.py
To determine if the user an access all fields of a particular table. This new method is needed, because on Azure the postgresql columns can have individual scope-based access. Django collects the full set of columns (select * from) when accessing a FK or M2M relation. This leads to permission error at the database level when accessing the API.
So, more specific access of columns is needed,
hence the extra helper method on userscopes.
> AB#101824 Add helper method to userscopes

- CHANGES.md
- setup.cfg
- src/schematools/types.py
- tests/conftest.py
- tests/files/datasets/kadastraleobjecten.json
- tests/files/datasets/subfield_auth.json
- tests/test_permissions_auth.py
Field with subfields were not protected by the scope of the main field.
E.g. 
```
"soortCultuurOnbebouwd": {
"auth": ["BRK/RO"],
"type": "object",
"properties": {
"code": {
"type": "string"
},
"omschrijving": {
"type": "string"
}
}
```
Whe accessing the subfield `soortCultuurOnbebouwdCode`, the scope
"BRK/RO" should be applied, however, it was not.
This PR fixes that bug.
> AB#101824 Fix auth property for subfields.

- CHANGES.md
- setup.cfg
- src/schematools/contrib/django/models.py
A stringified tuple was saved to the database.
Seems to be some kind of copy/paste error.
> Fix storing the display_field on the datasettable

- CHANGES.md
- setup.cfg
- src/schematools/exports/__init__.py
- src/schematools/exports/csv.py
- src/schematools/exports/geopackage.py
- src/schematools/exports/jsonlines.py
Sometimes zero columns are selected. Only open data is exported, so when columns are protected by a scope, those columns are not exported.
Furthermore, the temporal aspect was not added to the jsonlines export, so the whole history was exported.
> Do not write export files if not columns are selected

- src/schematools/contrib/django/models.py
Because it is a databasefield and it is directly used in sql queries, it is better to snake_case it.
> Fix casing of the id_field.

- setup.cfg
- src/schematools/_utils.py
- src/schematools/events/full.py
- src/schematools/permissions/auth.py
- src/schematools/types.py
- tests/test_events_full.py
- tests/test_indexes.py
See individual commits, it improves all aspects which showed up during DSO-API profiling.
The major improvement is no longer calling `__missing__()` for 800+ "auth" field access, which called `repr(self.data)` for a missing key.
It also includes the deepcopy-preventative measure, so DSO-API or any other code won't accidentally perform a `deepcopy()` of the schema data. In its current form this is too slow.
> Fix performance of "auth" field access

- CHANGES.md
- setup.cfg
This  blocks upgrading DSO-API
> Fix Django < 4.2 pinning

- .github/workflows/deplic.yaml
- .github/workflows/pre-commit.yml
- .github/workflows/test.yaml
- .pre-commit-config.yaml
- Dockerfile
- setup.cfg
Updated all references to python 3.13, also added python 3.12 to the test matrix.
Since the last successful test workflow on Github the `ubuntu:latest` image was updated from 22.04 to 24.04, which required an update to the gdal package. Should we pin the version of the test container to prevent this from happening again?
> Add compatibilty for python 3.13

- src/schematools/contrib/django/management/commands/change_dataset.py
As per python 3.12 distutils is deprecated. The only use of this was strtobool which has been reimplemented inline.
> Inline strtobool to replace deprecated distutils

- .pre-commit-hooks.yaml
- CHANGES.md
- setup.cfg
- src/schematools/__init__.py
- src/schematools/cli.py
- src/schematools/exceptions.py
- src/schematools/loaders.py
- src/schematools/types.py
- tests/conftest.py
- tests/files/duplicate_tests/scopes/GLEBZ/glebzscope.json
- tests/files/duplicate_tests/scopes/HARRY/harryscope.json
- tests/files/scopes/GLEBZ/glebzscope.json
- tests/files/scopes/HARRY/harryscope1.json
- tests/files/scopes/HARRY/harryscope2.json
- tests/test_loaders.py
[Task 135798](https://dev.azure.com/CloudCompetenceCenter/Data%20Diensten/_workitems/edit/135798): Add validate-scopes command to schema-tools cli
> Add validate scopes command

- CHANGES.md
- setup.cfg
- src/schematools/loaders.py
- src/schematools/types.py
- tests/files/datasets/metaschema2.json
- tests/files/scopes/HARRY/harryscope3.json
- tests/test_loaders.py
- tests/test_types.py
NB [#570] eerst mergen. ✅ 
Deze zorgt ervoor dat we voor de auth velden nu ook een ref naar een scope object kunnen verwerken. 
Voor nu houdt dit de bestaande return value `frozenset[str]` voor de auth velden in stand.
> Resolve refs in auth fields

- CHANGES.md
- setup.cfg
- src/schematools/types.py
- tests/files/scopes/GLEBZ/glebzscope.json
- tests/files/scopes/HARRY/harryscope1.json
- tests/files/scopes/HARRY/harryscope2.json
- tests/files/scopes/HARRY/harryscope3.json
- tests/test_loaders.py
Voegt de nieuwe velden toe aan de Scope class. 
Ook test geschreven voor de URL loader, aangezien deze nog niet getest werd. Wel optioneel gemaakt, want traag, we moeten evalueren of het de moeite waard is om dit bijvoorbeeld te testen in github workflow bij een merge.
> Update scope objects

- CHANGES.md
- setup.cfg
- src/schematools/cli.py
- src/schematools/loaders.py
- src/schematools/permissions/db.py
- src/schematools/types.py
- tests/conftest.py
- tests/files/datasets/gebieden_auth_scopes.json
- tests/test_loaders.py
- tests/test_permissions.py
- tests/test_types.py
`permissions apply` gebruikte de strings die op de auth velden zaten, maar prefereert nu scope objecten. 
- types DatasetSchema, DatasetTableSchema en DatasetFieldSchema hebben een aparte scopes property gekregen
- get_all_dataset_scopes gebruikt die .scopes properties om de scopes in te lezen. 
- rollen worden gebaseerd op de productiePackage veldnaam (waar we alleen het laatste gedeelte van gebruiken, dus exclusief de -p- van productie). 
- fallback op auth strings in stand gehouden ivm backwards compatibility
> Adapt permissions apply to prefer scopes

- src/schematools/cli.py
Dit commando wordt niet meer gebruikt, kan weg.
> Remove consume command

- CHANGES.md
- setup.cfg
- src/schematools/types.py
- tests/files/scopes/GLEBZ/glebzscope.json
- tests/files/scopes/HARRY/harryscope1.json
- tests/files/scopes/HARRY/harryscope2.json
- tests/files/scopes/HARRY/harryscope3.json
- tests/test_loaders.py
- tests/test_types.py
Deze [PR in amsterdam-schema](https://github.com/Amsterdam/amsterdam-schema/pull/1258) verandert de scopes objects enigszins. Deze PR matcht dat hier, zodat we in sync blijven.
> Update scope types in schema tools

- src/schematools/contrib/django/models.py
- src/schematools/types.py
- tests/test_types.py
De db_name en python_name van bestaande Scopes hadden een heleboel u_n_d_e_r_s_c_o_r_e_s, dat kwam omdat hij to_snake_case toepaste op een string met alleen maar hoofdletters. Dus eerst een .lower() toepassen.
> Fix scope db and python name

- CHANGES.md
- setup.cfg
- src/schematools/permissions/db.py
- src/schematools/types.py
- tests/django/fixtures.py
- tests/test_permissions.py
- tests/test_types.py
Dit was nog overgebleven van de byo-accesspackage feature. 
Ook een bug gevonden 😱  (die we impliciet verholpen door terug te vallen op auth velden). 
NB❗: De assumptie hierachter is dat voor alle bestaande auth strings die in gebruik zijn een scope object binnen amsterdam-schema bestaat.  
NB2❗: Als we DSO-API met deze versie willen laten werken, moeten we ook daar de `_find_scope_by_id` method monkeypatchen in de tests. Heb dat lokaal al werkend.
> Refactor scopes methods

- CHANGES.md
- docker-compose.yml
- setup.cfg
- src/schematools/contrib/django/factories.py
- src/schematools/contrib/django/faker/relate.py
- src/schematools/importer/ndjson.py
- src/schematools/types.py
- tests/django/test_mocking.py
- tests/django/test_model_mockers.py
- tests/django/test_models.py
- tests/test_export.py
- tests/test_import.py
- tests/test_indexes.py
- tests/test_ndjson.py
- tests/test_permissions.py
Major version is added to all table names to allow for multiple versions to co-exist. Django en sqlalchemy tests are fixed to reflect the new situation.
> Add major version to table names

- setup.cfg
- src/schematools/contrib/django/factories.py
- tests/django/conftest.py
Also django-db-comments requires psycopg2, which would block the upgrade.
> Fix db-comments, use native Django 4.2 logic for that

- CHANGES.md
- setup.cfg
- src/schematools/contrib/django/factories.py
- src/schematools/contrib/django/faker/relate.py
- src/schematools/types.py
- tests/django/test_mocking.py
- tests/django/test_model_mockers.py
- tests/django/test_models.py
Removed major version number from version name as it causes issues in the DSO-API for now. We will need this once we'll start to support multiple versions of a model, but for now this causes to much required changes in DSO-API.
> Remove version number from model name

- CHANGES.md
- setup.cfg
- src/schematools/loaders.py
Dit was erdoorheen geglipt. 
Heb deze versie getest en de github [workflow](https://github.com/Amsterdam/amsterdam-schema/actions/runs/14303082119/job/40080941661) in amsterdam-schema pikt dit wel goed op.
> Allow strings as path

- CHANGES.md
- setup.cfg
- src/schematools/types.py
- tests/files/datasets/gebieden.json
- tests/test_types.py
Zodat we dit gemakkelijk kunnen uitlezen in DSO-API en de velden kunnen bepalen die in de MVT view worden meegegeven bij elk zoomniveau.
> Add zoom props to DatasetTableSchema

- CHANGES.md
- setup.cfg
- src/schematools/contrib/django/management/commands/create_tables.py
- src/schematools/contrib/django/management/commands/create_views.py
- src/schematools/contrib/django/management/commands/import_schemas.py
- src/schematools/contrib/django/management/commands/migration_helpers.py
- src/schematools/contrib/django/management/commands/sqlmigrate_schema.py
- src/schematools/contrib/django/models.py
- tests/django/test_schema_import.py
- tests/files/datasets/hr_updated.json
Dit loopt over alle datasets heen en past de database tabellen aan indien nodig. Een eerdere validatiestap zorgt ervoor dat alleen branches gemerged worden die zorgen dat de alters backwards compatible zijn (i.e. alleen kolommen toevoegen). 
* --dry-run flag toegevoegd op het import_schemas commando
* logica van sqlmigrate_schema commando herbruikt => staat nu in migration_helpers.py
* een test voor --dry-run en voor de alters toegevoegd
* versie naar 7.5
* schoont de output/logs op: fixt 81710
NB: dit doet nog geen drop&replace voor de tabellen die op experimental staan.
> Autopatch database tables

- CHANGES.md
- setup.cfg
- src/schematools/validation.py
- tests/test_validation.py
Tables hebben een schema $ref, die door het script van Jasper voor het omschrijven van de dataset + tabellen naar v3 omgezet worden naar de laatste versie. Dit moet kunnen, omdat deze prop niet in de db terechtkomt, dus we skippen checks op deze property. 
Validatie van de ref zelf gebeurt elders al.
> ignore schema prop in table validation

- CHANGES.md
- setup.cfg
- src/schematools/cli.py
Deze errors voorkomen dat we de datasets kunnen updaten naar v3. Voor nu deze negeren, aangezien de bestaande database tabellen uitgaan van de verkeerde gegevens.
> Error handling v3

- CHANGES.md
- setup.cfg
- src/schematools/contrib/django/factories.py
- src/schematools/types.py
Dit zou de tabellen moeten aanmaken voor alle versies, ook de experimentele.
- alleen handmatig getest op lokale db
- nog geen drop/replace
> Create tables for all dataset versions

- CHANGES.md
- setup.cfg
- src/schematools/contrib/django/factories.py
- src/schematools/contrib/django/management/commands/create_tables.py
- tests/conftest.py
- tests/django/fixtures.py
- tests/django/test_models.py
- tests/files/datasets/metaschemav3/dataset.json
The new gat_all_tables functions introduced to be able to create multiple versions of a table caused issues in DSO API. I've added a flag to specifically request versioned tables used in create_tables only for now.
> Add flag to schema_model_factory to create versioned tables

- CHANGES.md
- setup.cfg
- src/schematools/contrib/django/factories.py
- src/schematools/contrib/django/models.py
- tests/django/test_models.py
Dit zorgt ervoor dat de relaties op de juiste manier worden resolved. 
Tests zijn gerepliceerd van andere model tests met juiste version suffixes erbij. 
TODO (later): schema_models_factory / model_factory uitfaseren.
> Make factory version aware

- src/schematools/permissions/db.py
- tests/test_permissions.py
This allows Terraform to link DSO-API to "role.filtered", while the SQL user gets "role" without the .filtered.
This way, DSO-API can access the mandatoryFilterSets columns, but the SQL user can't.
> Add ROLE.filtered roles for every created permission

- Makefile
- docker-compose.yml
- tests/django/conftest.py
fixed some things:
- postgres port conflicted with the one in dso-api, which was a PITA when switching between the two
- twine arg in the make upload command caused a prompt for API token, while this should be available in the .pypirc file. The repository arg was identical to its default value.
> DX upgrade

- .github/workflows/deplic.yaml
- .github/workflows/pre-commit.yml
- .github/workflows/test.yaml
- CHANGES.md
- setup.cfg
- src/schematools/exports/__init__.py
- src/schematools/exports/geopackage.py
De fix op v8 brak omdat psycopg3 niet lekker gaat op de code in `export_geopackages` en ik niet zo snel een oplossing kon vinden. Dus nu ook op laatste versie van voor die transitie, zodat de exports in ieder geval kunnen draaien.
> fix db name pt2

- CHANGES.md
- setup.cfg
- src/schematools/types.py
- tests/files/datasets/scope_filtering.json
- tests/test_types.py
Nieuwe class method voor `DatasetSchema` om velden uit de tabellen te filteren op basis van een lijst met scopes.
Het werkt zo:
- Je geeft een lijst met scopes mee aan `DatasetSchema.filter_on_scopes(scopes)`
-  Deze wordt doorgegeven aan de `DatasetSchema.json_data()` van en daarin aan `DatasetTableSchema.json_data()`.
- `inline_tables` wordt op `True` gezet, want daardoor gaan we daadwerkelijk door alle velden van alle tabellen. _Is dit wel een goede methode?_
- Tijdens het inlinen wordt met de `DatasetTableSchema.filter_on_scopes`-method de scopes-array omgezet in een UserScopes object _(ik kan UserScopes niet globaal importeren door een circular import)_, en daarmee wordt er bij elk veld gecheckt of gegeven scope toegang heeft tot het veld. Zo ja, dan wordt het opgeslagen en …
> Add method to filter table fields based on scope
